#!/bin/sh
# M72 verified-ref bridge must stay read-only and CMS-record-safe.
set -eu
root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
v="$root/src/GITVREF.EXEC"
g="$root/src/GIT.EXEC"
r="$root/src/GITREF2.REPO"
test -s "$v"
test -s "$g"
test -s "$r"
grep -Fxq "REF2 1" "$r"
grep -Fxq "HEAD refs/heads/main" "$r"
grep -Fxq "REF refs/heads/main 00D8D63229305230C8D37F884CE87F9E1A89468C" "$r"
grep -Fq "GITREC SHOWFULL GITFIX M15NEW" "$v"
grep -Fq "SHOW FULL ROOT CLOSURE VERIFIED" "$v"
grep -Fq "'FILEDEF SEL0 DISK M15SL0 PTR A'" "$v"
grep -Fq "'FILEDEF SEL1 DISK M15SL1 PTR A'" "$v"
grep -Fq "command = 'VERIFY-REF'" "$g"
grep -Fq "'EXEC GITVREF RESOLVE' rest" "$g"
grep -Fq "command = 'SHOW-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF SHOW' rest" "$g"
grep -Fq "command = 'LOG-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF LOG' rest" "$g"
grep -Fq "command = 'LOGDAG-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF DAG' rest" "$g"
grep -Fq "command = 'HISTORYPATH-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTPATH' rest" "$g"
grep -Fq "command = 'HISTORYCHANGES-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTCHG' rest" "$g"
grep -Fq "command='HISTCHG'" "$v"
grep -Fq "HISTORYCHANGES FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYCHANGES DISTINCT PATH OIDS" "$v"
grep -Fq "HISTORYCHANGES STATUS' status" "$v"
grep -Fq "status='UNCHANGED'" "$v"
grep -Fq "status='CHANGED'" "$v"
grep -Fq "HISTORYCHANGES VERSION' vi 'OID' version.vi" "$v"
grep -Fq "'COUNT' freq.vi 'MINDEPTH' mindepth.vi" "$v"
grep -Fq "'MAXDEPTH' maxdepth.vi" "$v"
grep -Fq "curdepth=word(out.ci,5)" "$v"
grep -Fq "mindepth.distinct=curdepth" "$v"
grep -Fq "maxdepth.distinct=curdepth" "$v"
grep -Fq "parsednodes=parsednodes+1" "$v"
grep -Fq "if havepath=1 then return 'ERROR'" "$v"
grep -Fq "if parsednodes\\=nodes then return 'ERROR'" "$v"
grep -Fq "version.distinct=poid" "$v"
grep -Fq "freq.distinct=1" "$v"
grep -Fq "freq.vi=freq.vi+1" "$v"
grep -Fq "pathoids\\=nodes" "$v"
grep -Fq "GITREC HISTORYDAGPATH GITFIX M15NEW" "$v"
grep -Fq "HISTORYDAGPATH FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "GITREC LOGDAGFULL GITFIX M15NEW" "$v"
grep -Fq "LOGDAG FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "GITREC LOGFULL GITFIX M15NEW" "$v"
grep -Fq "LOG FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "command='READ'" "$v"
grep -Fq "GITREC PATHFULLCAT GITFIX M15NEW" "$v"
grep -Fq "COMMIT ROOT FULL CLOSURE VERIFIED" "$v"
grep -Fq "command = 'READ-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF READ' rest" "$g"
grep -Fq "pathasciihex:" "$v"
grep -Fq "command='DIR'" "$v"
grep -Fq "GITREC PATHFULLDIR GITFIX M15NEW" "$v"
grep -Fq "command = 'DIR-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF DIR' rest" "$g"
if grep -Ei "(DISKW|ERASE|COPYFILE|GENWRITE|SELOUT|IDXOUT|FIDXOUT|GENOUT)" "$v"; then
 echo "FAIL: verified-ref bridge contains persistent write path" >&2
 exit 1
fi
awk 'length($0)>80 {print "FAIL: GITVREF record >80 columns:", NR; bad=1}
     END {exit bad}' "$v"
awk 'length($0)>80 {print "FAIL: GITREF2 record >80 columns:", NR; bad=1}
     END {exit bad}' "$r"
echo "M72 FIXED REF2 VERSION-DEPTH RANGE GUARDS PASSED"
