#!/bin/sh
set -eu
root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
x="$root/src/M155CHK.EXEC"
test -s "$x"
grep -Fq "PIPE CMS EXEC GITVREF HISTFPCHR" "$x"
grep -Fq "PIPE CMS EXEC GITVREF HISTFPEVT" "$x"
grep -Fq "HISTORYFIRSTPRESENCECHRONOLOGY FULL SNAPSHOTS VERIFIED" "$x"
grep -Fq "HISTORYFIRSTPRESENCECHRONOLOGY PRESENCE RUNS 2" "$x"
grep -Fq "HISTORYFIRSTPRESENCECHRONOLOGY AUTHOR ZERO RUNS 2" "$x"
grep -Fq "HISTORYFIRSTPRESENCECHRONOLOGY COMMITTER ZERO RUNS 2" "$x"
grep -Fq "HISTORYFIRSTPRESENCEEVENTS FULL SNAPSHOTS VERIFIED" "$x"
grep -Fq "HISTORYFIRSTPRESENCEEVENTS EVENTS 1" "$x"
grep -Fq "HISTORYFIRSTPRESENCEEVENTS EVENT 1 FROM RUN 1 TO RUN 2" "$x"
grep -Fq "HISTORYFIRSTPRESENCEEVENTS EVENT 1 EDGE 1 STATUS DELETED" "$x"
grep -Fq "M155 COMPACT TARGET GATE PASS" "$x"
if grep -Ei "(DISKW|ERASE|COPYFILE|GENWRITE|SELOUT|IDXOUT|FIDXOUT|GENOUT)" "$x"; then
 echo "FAIL: M155 compact gate contains persistent write path" >&2
 exit 1
fi
awk 'length($0)>80 {print "FAIL: M155CHK record >80:",NR; bad=1}
     END {exit bad}' "$x"
echo "M155 COMPACT CMS TARGET GATE SOURCE CHECK PASSED"
