#!/bin/sh
# M139 authenticated first-parent subject guards.
set -eu
root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
v="$root/src/GITVREF.EXEC"
g="$root/src/GIT.EXEC"
r="$root/src/GITREF2.REPO"
rec="$root/src/GITREC.C"
test -s "$v"
test -s "$g"
test -s "$r"
test -s "$rec"
grep -Fxq "REF2 1" "$r"
grep -Fxq "HEAD refs/heads/main" "$r"
grep -Fxq "REF refs/heads/main 00D8D63229305230C8D37F884CE87F9E1A89468C" "$r"
grep -Fq "GITREC SHOWFULL GITFIX M15NEW" "$v"
grep -Fq "SHOW FULL ROOT CLOSURE VERIFIED" "$v"
grep -Fq "'FILEDEF SEL0 DISK M15SL0 PTR A'" "$v"
grep -Fq "'FILEDEF SEL1 DISK M15SL1 PTR A'" "$v"
grep -Fq "command = 'VERIFY-REF'" "$g"
grep -Fq "'EXEC GITVREF RESOLVE' rest" "$g"
grep -Fq "command = 'SHOW-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF SHOW' rest" "$g"
grep -Fq "command = 'LOG-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF LOG' rest" "$g"
grep -Fq "command = 'LOGDAG-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF DAG' rest" "$g"
grep -Fq "command = 'HISTORYPATH-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTPATH' rest" "$g"
grep -Fq "command = 'HISTORYCHANGES-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTCHG' rest" "$g"
grep -Fq "command = 'HISTORYEDGES-REF-FULL'" "$g"
grep -Fq "command = 'HISTORYDIFFS-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTDIFF' rest" "$g"
grep -Fq "command = 'HISTORYSTATE-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTSTATE' rest" "$g"
grep -Fq "command = 'HISTORYLOG-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTLOG' rest" "$g"
grep -Fq "command = 'HISTORYSTATUS-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTSTATUS' rest" "$g"
grep -Fq "command = 'HISTORYNEAREST-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTNEAR' rest" "$g"
grep -Fq "command = 'HISTORYTRANSITIONS-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTTRANS' rest" "$g"
grep -Fq "command = 'HISTORYREPORT-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTREPORT' rest" "$g"
grep -Fq "command = 'HISTORYBOUNDS-REF-FULL'" "$g"
grep -Fq "command = 'LEVEL'" "$g"
grep -Fq "command = 'HISTORYCHRONOLOGY-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTCHRON' rest" "$g"
grep -Fq "command = 'HISTORYACTORS-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTACTORS' rest" "$g"
grep -Fq "command = 'HISTORYSUBJECTS-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTSUBJECTS' rest" "$g"
grep -Fq "command = 'HISTORYBODIES-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTBODIES' rest" "$g"
grep -Fq "command = 'HISTORYTOPOLOGY-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTTOPO' rest" "$g"
grep -Fq "command = 'HISTORYPARENTS-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTPARENTS' rest" "$g"
grep -Fq "command = 'HISTORYPARENTSLOTS-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTSLOTS' rest" "$g"
grep -Fq "command = 'HISTORYEDGEROLES-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTROLES' rest" "$g"
grep -Fq "command = 'HISTORYFIRSTPARENT-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTFIRST' rest" "$g"
grep -Fq "command = 'HISTORYFIRSTCHANGES-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTFCHG' rest" "$g"
grep -Fq "command = 'HISTORYFIRSTTRANSITIONS-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTFTRANS' rest" "$g"
grep -Fq "command = 'HISTORYFIRSTCHRONOLOGY-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTFCHRON' rest" "$g"
grep -Fq "command = 'HISTORYFIRSTACTORS-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTFACTORS' rest" "$g"
grep -Fq "command = 'HISTORYFIRSTSUBJECTS-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTFSUBJ' rest" "$g"
grep -Fq "GIT EXEC LEVEL M139" "$g"
grep -Fq "GITVREF EXEC LEVEL M139" "$v"
grep -Fq "GIT EXEC LEVEL M139" "$g"
grep -Fq "GITVREF EXEC LEVEL MISMATCH" "$g"
grep -Fq "GITVREF EXEC LEVEL M139" "$v"
grep -Fxq "numeric digits 20" "$v"
grep -Fq "rawwanted=wanted" "$v"
grep -Fq "length(direct)=40" "$v"
grep -Fq "call directinput command" "$v"
grep -Fq "reskind='COMMIT'" "$v"
grep -Fq "if left(c,4)='HIST' then return 1" "$v"
grep -Fq "VERIFIED COMMIT" "$v"
grep -Fq "else say 'VERIFIED REF' spec oid" "$v"
grep -Fq "rec_ident_when" "$rec"
grep -Fq "rec_commit_times" "$rec"
grep -Fq "HISTORYDAGSTATE AUTHOR TIME %lu TZMIN %d" "$rec"
grep -Fq "HISTORYDAGSTATE COMMITTER TIME %lu TZMIN %d" "$rec"
grep -Fq "HISTORYDAGSTATE AIDENT BYTES %lu PREFIXBYTES %u" "$rec"
grep -Fq "HISTORYDAGSTATE CIDENT BYTES %lu PREFIXBYTES %u" "$rec"
grep -Fq "HISTORYDAGSTATE AIDENTHEX" "$rec"
grep -Fq "HISTORYDAGSTATE CIDENTHEX" "$rec"
grep -Fq "HISTORYDAGSTATE AIDENT BLOBID" "$rec"
grep -Fq "HISTORYDAGSTATE CIDENT BLOBID" "$rec"
grep -Fq "author_ident_prefix_bytes" "$rec"
grep -Fq "commit_ident_prefix_bytes" "$rec"
grep -Fq "saidentbytes.curnode=ib" "$v"
grep -Fq "scidentbytes.curnode=ib" "$v"
grep -Fq "CAIDENTHEX" "$v"
grep -Fq "PCIDENTHEX" "$v"
grep -Fq "CAIDENT BLOBID" "$v"
grep -Fq "PCIDENT BLOBID" "$v"
grep -Fq "stateactors:" "$v"
grep -Fq "HISTORYACTORS FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYACTORS AUTHORS' authors" "$v"
grep -Fq "HISTORYACTORS COMMITTERS' committers" "$v"
grep -Fq "statesubjects:" "$v"
grep -Fq "HISTORYSUBJECTS FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYSUBJECTS SUBJECTS' subjects" "$v"
grep -Fq "CHILDSUBJECT BLOBID" "$v"
grep -Fq "PARENTSUBJECT BLOBID" "$v"
grep -Fq "statebodies:" "$v"
grep -Fq "HISTORYBODIES FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYBODIES BODIES' bodies" "$v"
grep -Fq "CHILDMESSAGE BLOBID" "$v"
grep -Fq "PARENTMESSAGE BLOBID" "$v"
grep -Fq "statetopology:" "$v"
grep -Fq "HISTORYTOPOLOGY FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYTOPOLOGY MAX PARENTS" "$v"
grep -Fq "soutedges.ni\=suniqueparents.ni" "$v"
grep -Fq "stateparents:" "$v"
grep -Fq "HISTORYPARENTS FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYPARENTS FIRST FOLLOWED" "$v"
grep -Fq "firstmatches\=1" "$v"
grep -Fq "stateparentslots:" "$v"
grep -Fq "HISTORYPARENTSLOTS FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYPARENTSLOTS DUPLICATE SLOTS" "$v"
grep -Fq "sslotnodecount.ni\=sparents.ni" "$v"
grep -Fq "sslotdistinct.ni\=suniqueparents.ni" "$v"
grep -Fq "stateedgeroles:" "$v"
grep -Fq "HISTORYEDGEROLES FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYEDGEROLES FIRST EDGES" "$v"
grep -Fq "HISTORYEDGEROLES MERGE EDGES" "$v"
grep -Fq "HISTORYEDGEROLES MULTISLOT EDGES" "$v"
grep -Fq "duplicate\=sslotcount-sedgecount" "$v"
grep -Fq "firstedges\=expectedfirst" "$v"
grep -Fq "if eroleslots.ei<1 then return 8" "$v"
grep -Fq "if erolemin.ei<2 then return 8" "$v"
grep -Fq "'ROLE' role" "$v"
grep -Fq "'MINORDINAL' erolemin.ei 'MAXORDINAL' erolemax.ei" "$v"
grep -Fq "statefirstparent:" "$v"
grep -Fq "HISTORYFIRSTPARENT FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYFIRSTPARENT CHAIN NODES" "$v"
grep -Fq "HISTORYFIRSTPARENT OFFCHAIN EDGES" "$v"
grep -Fq "HISTORYFIRSTPARENT TRUNCATED" "$v"
grep -Fq "buildfirstparent:" "$v"
grep -Fq "if fpseen.next=1 then return 'ERROR'" "$v"
grep -Fq "if edgeok=0 then return 'ERROR'" "$v"
grep -Fq "chainedges=fpcount-1" "$v"
grep -Fq "offedges=sedgecount-chainedges" "$v"
grep -Fq "if sdepth.cur>=depth then do" "$v"
grep -Fq "if sparents.cur>0 then truncated=1" "$v"
grep -Fq "statefirstchanges:" "$v"
grep -Fq "HISTORYFIRSTCHANGES FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYFIRSTCHANGES CHAIN EDGES" "$v"
grep -Fq "HISTORYFIRSTCHANGES CHANGES" "$v"
grep -Fq "HISTORYFIRSTCHANGES DELETED" "$v"
grep -Fq "fstatus.fi='DELETED'" "$v"
grep -Fq "fstatus.fi='MODIFIED'" "$v"
grep -Fq "fstatus.fi='ADDED'" "$v"
grep -Fq "fstatus.fi='UNCHANGED'" "$v"
grep -Fq "fchanged\=fadd+fdelete+fmodify" "$v"
grep -Fq "fadd+fdelete+fmodify+funchanged\=chainedges" "$v"
grep -Fq "'CHILDSTATE' cs" "$v"
grep -Fq "'PARENTSTATE' ps" "$v"
grep -Fq "'CHILDOID' soid.ec" "$v"
grep -Fq "'PARENTOID' soid.ep" "$v"
grep -Fq "statefirsttransitions:" "$v"
grep -Fq "HISTORYFIRSTTRANSITIONS FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYFIRSTTRANSITIONS TRANSITIONS" "$v"
grep -Fq "HISTORYFIRSTTRANSITIONS CHANGED TRANSITIONS" "$v"
grep -Fq "HISTORYFIRSTTRANSITIONS DELETED EDGES" "$v"
grep -Fq "ftstatus.ti='DELETED'" "$v"
grep -Fq "ftstatus.ti='MODIFIED'" "$v"
grep -Fq "ftstatus.ti='ADDED'" "$v"
grep -Fq "ftstatus.ti='UNCHANGED'" "$v"
grep -Fq "fttotal\=chainedges" "$v"
grep -Fq "ftchangededges\=ftadd+ftdelete+ftmodify" "$v"
grep -Fq "call stateversions" "$v"
grep -Fq "call buildfirstparent" "$v"
grep -Fq "HISTORYFIRSTTRANSITIONS STATE 0 ABSENT" "$v"
grep -Fq "'PRESENT OID' sveroid.vi" "$v"
grep -Fq "'CHILDSTATE' cv" "$v"
grep -Fq "'PARENTSTATE' pv 'COUNT' ftcount.ti" "$v"
grep -Fq "'PARENTOID' sveroid.pv" "$v"
grep -Fq "statefirstchron:" "$v"
grep -Fq "HISTORYFIRSTCHRONOLOGY FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYFIRSTCHRONOLOGY AUTHOR POSITIVE EDGES" "$v"
grep -Fq "HISTORYFIRSTCHRONOLOGY COMMITTER POSITIVE EDGES" "$v"
grep -Fq "HISTORYFIRSTCHRONOLOGY LAG ZERO NODES" "$v"
grep -Fq "'AUTHOR DELTA SECONDS' ad" "$v"
grep -Fq "'COMMITTER DELTA SECONDS' cd" "$v"
grep -Fq "'LAG SECONDS' lag" "$v"
grep -Fq "fapos+fazero+faneg\=chainedges" "$v"
grep -Fq "flpos+flzero+flneg\=fpcount" "$v"
grep -Fq "statefirstactors:" "$v"
grep -Fq "HISTORYFIRSTACTORS FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYFIRSTACTORS AUTHOR SAME EDGES" "$v"
grep -Fq "HISTORYFIRSTACTORS AUTHOR CHANGED EDGES" "$v"
grep -Fq "HISTORYFIRSTACTORS COMMITTER SAME EDGES" "$v"
grep -Fq "HISTORYFIRSTACTORS COMMITTER CHANGED EDGES" "$v"
grep -Fq "HISTORYFIRSTACTORS AUTHOR HANDOFFS" "$v"
grep -Fq "HISTORYFIRSTACTORS COMMITTER HANDOFFS" "$v"
grep -Fq "fasame+fachanged\=chainedges" "$v"
grep -Fq "fcsame+fcchanged\=chainedges" "$v"
grep -Fq "'AUTHOR STATUS' ast" "$v"
grep -Fq "'COMMITTER STATUS' cst" "$v"
grep -Fq "'AUTHOR CHILD BLOBID' saidentid.ec" "$v"
grep -Fq "'COMMITTER PARENT BLOBID' scidentid.ep" "$v"
grep -Fq "statefirstsubjects:" "$v"
grep -Fq "HISTORYFIRSTSUBJECTS FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYFIRSTSUBJECTS SAME EDGES" "$v"
grep -Fq "HISTORYFIRSTSUBJECTS CHANGED EDGES" "$v"
grep -Fq "HISTORYFIRSTSUBJECTS HANDOFFS" "$v"
grep -Fq "HISTORYFIRSTSUBJECTS CHANGED HANDOFFS" "$v"
grep -Fq "fssame+fschanged\=chainedges" "$v"
grep -Fq "'CHILD BLOBID' ssubid.ec" "$v"
grep -Fq "'PARENT BLOBID' ssubid.ep" "$v"
grep -Fq "'CHILD BYTES' ssubbytes.ec" "$v"
grep -Fq "'PARENT BYTES' ssubbytes.ep" "$v"
grep -Fq "HISTORYDAGSTATE MESSAGE BYTES %lu" "$rec"
grep -Fq "HISTORYDAGSTATE SUBJECT BYTES %lu PREFIXBYTES %u" "$rec"
grep -Fq "HISTORYDAGSTATE SUBJECTHEX" "$rec"
grep -Fq "HISTORYDAGSTATE SUBJECT BLOBID" "$rec"
grep -Fq "HISTORYDAGSTATE MESSAGE BLOBID" "$rec"
grep -Fq "HISTORYDAGSTATE PARENTS %lu UNIQUE %lu" "$rec"
grep -Fq "HISTORYDAGSTATE FIRSTPARENT" "$rec"
grep -Fq "HISTORYDAGSTATE PARENTSEQ BLOBID" "$rec"
grep -Fq "seq+(*parents)*20UL" "$rec"
grep -Fq "HISTORYDAGSTATE SLOT CHILD %u ORDINAL %u PARENT %u" "$rec"
grep -Fq "HISTORYDAGSTATE SLOTS %u" "$rec"
grep -Fq "parent_slot_node" "$rec"
grep -Fq "subject_prefix_bytes" "$rec"
grep -Fq "ssubbytes.curnode=sb" "$v"
grep -Fq "ssubprefix.curnode=sp" "$v"
grep -Fq "ssubhex.curnode=sh" "$v"
grep -Fq "CHILDSUBJECT BYTES" "$v"
grep -Fq "PARENTSUBJECT BYTES" "$v"
grep -Fq "sauthorwhen.curnode=aw" "$v"
grep -Fq "scommitwhen.curnode=cw" "$v"
grep -Fq "smsgbytes.curnode=mb" "$v"
grep -Fq "emitnodechron:" "$v"
grep -Fq "emitpairchron:" "$v"
grep -Fq "COMMITTER DELTA SECONDS" "$v"
grep -Fq "AUTHOR DELTA SECONDS" "$v"
grep -Fq "AUTHOR TO COMMITTER LAG SECONDS" "$v"
grep -Fq "statechron:" "$v"
grep -Fq "HISTORYCHRONOLOGY FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYCHRONOLOGY AUTHOR NEGATIVE EDGES" "$v"
grep -Fq "HISTORYCHRONOLOGY COMMITTER NEGATIVE EDGES" "$v"
grep -Fq "HISTORYCHRONOLOGY LAG NEGATIVE NODES" "$v"
grep -Fq "if command='LEVEL' then do" "$v"
grep -Fq "'EXEC GITVREF HISTBOUNDS' rest" "$g"
grep -Fq "'EXEC GITVREF HISTEDGE' rest" "$g"
grep -Fq "command='HISTCHG'" "$v"
grep -Fq "HISTORYCHANGES FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYCHANGES DISTINCT PATH OIDS" "$v"
grep -Fq "HISTORYCHANGES STATUS' status" "$v"
grep -Fq "status='UNCHANGED'" "$v"
grep -Fq "status='CHANGED'" "$v"
grep -Fq "HISTORYCHANGES VERSION' vi 'OID' version.vi" "$v"
grep -Fq "'COUNT' freq.vi 'MINDEPTH' mindepth.vi" "$v"
grep -Fq "'MAXDEPTH' maxdepth.vi" "$v"
grep -Fq "curdepth=word(out.ci,5)" "$v"
grep -Fq "mindepth.distinct=curdepth" "$v"
grep -Fq "maxdepth.distinct=curdepth" "$v"
grep -Fq "parsednodes=parsednodes+1" "$v"
grep -Fq "if havepath=1 then return 'ERROR'" "$v"
grep -Fq "if parsednodes\\=nodes then return 'ERROR'" "$v"
grep -Fq "curcommit=translate(word(out.ci,3))" "$v"
grep -Fq "MINDEPTHCOMMIT' mincommit.vi" "$v"
grep -Fq "MAXDEPTHCOMMIT' maxcommit.vi" "$v"
grep -Fq "mincommit.distinct=curcommit" "$v"
grep -Fq "maxcommit.distinct=curcommit" "$v"
grep -Fq "HISTORYCHANGES VERSION' vi 'TYPE' vtype.vi 'SIZE' vsize.vi" "$v"
grep -Fq "curtype=word(out.ci,4)" "$v"
grep -Fq "cursize=word(out.ci,6)" "$v"
grep -Fq "if curtype<1 | curtype>3 then return 'ERROR'" "$v"
grep -Fq "if vtype.vi\\=curtype | vsize.vi\\=cursize then return 'ERROR'" "$v"
grep -Fq "HISTORYCHANGES VERSION' vi 'DEPTHS' depthtext.vi" "$v"
grep -Fq "depthtext.vi=result" "$v"
grep -Fq "vcommit.distinct.1=curcommit" "$v"
grep -Fq "vdepth.distinct.1=curdepth" "$v"
grep -Fq "vcidx=freq.vi" "$v"
grep -Fq "vcommit.vi.vcidx=curcommit" "$v"
grep -Fq "vdepth.vi.vcidx=curdepth" "$v"
grep -Fq "HISTORYCHANGES VERSION' vi 'COMMIT' vcommit.vi.ci" "$v"
grep -Fq "'DEPTH' vdepth.vi.ci" "$v"
grep -Fq "datatype(vdepth.vi.ci,'W')" "$v"
grep -Fq "curnode=word(out.ci,3)" "$v"
grep -Fq "curnode\\=parsednodes | curnode>64" "$v"
grep -Fq "seencommit.curcommit=1" "$v"
grep -Fq "curtree=translate(word(out.ci,3))" "$v"
grep -Fq "havetree=1" "$v"
grep -Fq "vnode.distinct.1=curnode" "$v"
grep -Fq "vtree.distinct.1=curtree" "$v"
grep -Fq "vnode.vi.vcidx=curnode" "$v"
grep -Fq "vtree.vi.vcidx=curtree" "$v"
grep -Fq "members=members+freq.vi" "$v"
grep -Fq "if members\\=nodes then exit 8" "$v"
grep -Fq "verify(vcommit.vi.ci,'0123456789ABCDEF')" "$v"
grep -Fq "verify(vtree.vi.ci,'0123456789ABCDEF')" "$v"
grep -Fq "HISTORYCHANGES VERSION' vi 'NODE' vnode.vi.ci" "$v"
grep -Fq "'TREE' vtree.vi.ci" "$v"
grep -Fq "depthseen.distinct.curdepth=1" "$v"
grep -Fq "depthseen.vi.curdepth=1" "$v"
grep -Fq "depthlist:" "$v"
grep -Fq "version.distinct=poid" "$v"
grep -Fq "vi=distinct" "$v"
grep -Fq "command='HISTPATH' & word(out.i,1)='HISTORYDAGPATH'" "$v"
grep -Fq "(word(out.i,2)='EDGE' | word(out.i,2)='EDGES')" "$v"
grep -Fq "freq.distinct=1" "$v"
grep -Fq "freq.vi=freq.vi+1" "$v"
grep -Fq "pathoids\\=nodes" "$v"
grep -Fq "GITREC HISTORYDAGPATH GITFIX M15NEW" "$v"
grep -Fq "HISTORYDAGPATH FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYDAGPATH EDGE CHILD %u PARENT %u" "$rec"
grep -Fq "HISTORYDAGPATH EDGES %u" "$rec"
grep -Fq "edge[head][pidx]=1" "$rec"
grep -Fq "nodeversion.curnode=vi" "$v"
grep -Fq "edgekey.ec.ep=1" "$v"
grep -Fq "parentseen.ep=1" "$v"
grep -Fq "if parentseen.1=1 then return 'ERROR'" "$v"
grep -Fq "HISTORYCHANGES CHANGED EDGES" "$v"
grep -Fq "HISTORYCHANGES UNCHANGED EDGES" "$v"
grep -Fq "CHILDVERSION' edgecv.ei" "$v"
grep -Fq "PARENTVERSION' edgepv.ei" "$v"
grep -Fq "STATUS' edgestatus.ei" "$v"
grep -Fq "command='HISTCHG' | command='HISTEDGE'" "$v"
grep -Fq "HISTORYEDGES FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYEDGES VERSIONS" "$v"
grep -Fq "HISTORYEDGES VERSION' vi 'OID' version.vi" "$v"
grep -Fq "HISTORYEDGES CHANGED EDGES" "$v"
grep -Fq "HISTORYEDGES UNCHANGED EDGES" "$v"
grep -Fq "HISTORYEDGES EDGE' ei 'CHILDVERSION' edgecv.ei" "$v"
grep -Fq "HISTORYEDGES EDGE' ei 'STATUS' edgestatus.ei" "$v"
grep -Fq "pairchild.pairs=cv" "$v"
grep -Fq "pairparent.pairs=pv" "$v"
grep -Fq "paircount.pairs=1" "$v"
grep -Fq "HISTORYEDGES TRANSITIONS" "$v"
grep -Fq "HISTORYCHANGES TRANSITIONS" "$v"
grep -Fq "GITREC HISTORYDAGSTATE GITFIX M15NEW" "$v"
grep -Fq "HISTORYDAGSTATE FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYDAGSTATE PATH PRESENT TYPE %d SIZE %lu" "$rec"
grep -Fq "HISTORYDAGSTATE PATH ABSENT" "$rec"
grep -Fq "rec_root_path_state" "$rec"
grep -Fq "statecheck:" "$v"
grep -Fq "stateemit:" "$v"
grep -Fq "statelog:" "$v"
grep -Fq "snodever.ni=0" "$v"
grep -Fq "snodever.ni=vi" "$v"
grep -Fq "if snodever.ni<0 | snodever.ni>sversions then return 'ERROR'" "$v"
grep -Fq "stateclass:" "$v"
grep -Fq "schangemin=9" "$v"
grep -Fq "schangemax=-1" "$v"
grep -Fq "snearcount=0" "$v"
grep -Fq "if schanged\=sadd+sdelete+smodify then return 'ERROR'" "$v"
grep -Fq "statestatus:" "$v"
grep -Fq "HISTORYSTATUS FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYSTATUS VERSIONS' sversions" "$v"
grep -Fq "HISTORYSTATUS NEAREST CHANGE DEPTH' schangemin" "$v"
grep -Fq "HISTORYSTATUS FARTHEST CHANGE DEPTH' schangemax" "$v"
grep -Fq "HISTORYSTATUS NEAREST CHANGES' snearcount" "$v"
grep -Fq "HISTORYSTATUS PATH STATUS' slifecycle" "$v"
grep -Fq "HISTORYSTATUS ADDED EDGES' sadd" "$v"
grep -Fq "HISTORYSTATUS DELETED EDGES' sdelete" "$v"
grep -Fq "HISTORYSTATUS MODIFIED EDGES' smodify" "$v"
grep -Fq "HISTORYLOG FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYLOG CHANGES' schanged" "$v"
grep -Fq "HISTORYLOG CHANGE' ei 'STATUS' sstatus.ei" "$v"
grep -Fq "HISTORYLOG NEAREST CHANGE DEPTH' schangemin" "$v"
grep -Fq "HISTORYLOG FARTHEST CHANGE DEPTH' schangemax" "$v"
grep -Fq "HISTORYLOG CHANGE' ei 'CHILDCOMMIT' scommit.ec" "$v"
grep -Fq "HISTORYLOG CHANGE' ei 'PARENTCOMMIT' scommit.ep" "$v"
grep -Fq "HISTORYSTATE FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYSTATE STATUS' slifecycle" "$v"
grep -Fq "HISTORYSTATE PRESENT' spresentcount" "$v"
grep -Fq "HISTORYSTATE ABSENT' sabsecount" "$v"
grep -Fq "HISTORYDIFFS PATH STATUS' slifecycle" "$v"
grep -Fq "HISTORYDIFFS PRESENT' spresentcount" "$v"
grep -Fq "HISTORYDIFFS ABSENT' sabsecount" "$v"
grep -Fq "HISTORYSTATE NODE' ni 'STATE' ns" "$v"
grep -Fq "HISTORYSTATE NODE' ni 'OID' soid.ni" "$v"
grep -Fq "HISTORYSTATE EDGE' ei 'CHILD' sedgechild.ei" "$v"
grep -Fq "statediff:" "$v"
grep -Fq "HISTORYDIFFS ADDED EDGES" "$v"
grep -Fq "HISTORYDIFFS DELETED EDGES" "$v"
grep -Fq "HISTORYDIFFS MODIFIED EDGES" "$v"
grep -Fq "HISTORYDIFFS UNCHANGED EDGES" "$v"
grep -Fq "sstatus.ei='ADDED'" "$v"
grep -Fq "sstatus.ei='DELETED'" "$v"
grep -Fq "sstatus.ei='MODIFIED'" "$v"
grep -Fq "HISTORYDIFFS EDGE' ei 'CHILDSTATE' cs" "$v"
grep -Fq "'PARENTSTATE' ps" "$v"
grep -Fq "HISTORYDIFFS FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYDIFFS NEAREST CHANGE DEPTH' schangemin" "$v"
grep -Fq "HISTORYDIFFS FARTHEST CHANGE DEPTH' schangemax" "$v"
grep -Fq "statetrans:" "$v"
grep -Fq "HISTORYTRANSITIONS FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "emittranschron:" "$v"
grep -Fq "AUTHOR MIN DELTA SECONDS" "$v"
grep -Fq "AUTHOR MAX DELTA SECONDS" "$v"
grep -Fq "COMMITTER MIN DELTA SECONDS" "$v"
grep -Fq "COMMITTER MAX DELTA SECONDS" "$v"
grep -Fq "AUTHOR NEGATIVE EDGES" "$v"
grep -Fq "COMMITTER NEGATIVE EDGES" "$v"
grep -Fq "call emittranschron 'HISTORYTRANSITIONS',ti" "$v"
grep -Fq "call emittranschron 'HISTORYREPORT',ti" "$v"
grep -Fq "call emittranschron 'HISTORYDIFFS',ti" "$v"
grep -Fq "statereport:" "$v"
grep -Fq "statebounds:" "$v"
grep -Fq "HISTORYBOUNDS FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYBOUNDS NEAREST DEPTH' schangemin" "$v"
grep -Fq "HISTORYBOUNDS FARTHEST DEPTH' schangemax" "$v"
grep -Fq "HISTORYBOUNDS BOUNDARY CHANGES' boundcount" "$v"
grep -Fq "'BOUND' bound" "$v"
grep -Fq "HISTORYREPORT FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYREPORT TRANSITIONS' trpairs" "$v"
grep -Fq "HISTORYREPORT CHANGE' change 'EDGE' ei" "$v"
grep -Fq "HISTORYREPORT NEAREST CHANGE DEPTH' schangemin" "$v"
grep -Fq "HISTORYTRANSITIONS STATE 0 ABSENT" "$v"
grep -Fq "HISTORYTRANSITIONS TRANSITIONS' trpairs" "$v"
grep -Fq "HISTORYTRANSITIONS CHANGED TRANSITIONS' trchanged" "$v"
grep -Fq "HISTORYTRANSITIONS TRANSITION' ti 'CHILDSTATE' cv" "$v"
grep -Fq "HISTORYTRANSITIONS TRANSITION' ti 'STATUS' trstatus.ti" "$v"
grep -Fq "statenear:" "$v"
grep -Fq "HISTORYNEAREST FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYNEAREST DEPTH' schangemin" "$v"
grep -Fq "HISTORYNEAREST MATCHES' snearcount" "$v"
grep -Fq "HISTORYNEAREST CHANGE' match 'EDGE' ei" "$v"
grep -Fq "HISTORYDIFFS CHANGED EDGES" "$v"
grep -Fq "HISTORYDIFFS STATUS" "$v"
grep -Fq "HISTORYEDGES TRANSITION' ti 'CHILDOID' version.cv" "$v"
grep -Fq "HISTORYCHANGES TRANSITION' ti 'PARENTOID' version.pv" "$v"
grep -Fq "if distinct=1 & changededges\\=0 then exit 8" "$v"
grep -Fq "if distinct>1 & changededges=0 then exit 8" "$v"
grep -Fq "GITREC LOGDAGFULL GITFIX M15NEW" "$v"
grep -Fq "LOGDAG FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "GITREC LOGFULL GITFIX M15NEW" "$v"
grep -Fq "LOG FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "command='READ'" "$v"
grep -Fq "GITREC PATHFULLCAT GITFIX M15NEW" "$v"
grep -Fq "COMMIT ROOT FULL CLOSURE VERIFIED" "$v"
grep -Fq "command = 'READ-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF READ' rest" "$g"
grep -Fq "pathasciihex:" "$v"
grep -Fq "command='DIR'" "$v"
grep -Fq "GITREC PATHFULLDIR GITFIX M15NEW" "$v"
grep -Fq "command = 'DIR-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF DIR' rest" "$g"
if grep -Ei "(DISKW|ERASE|COPYFILE|GENWRITE|SELOUT|IDXOUT|FIDXOUT|GENOUT)" "$v"; then
 echo "FAIL: verified-ref bridge contains persistent write path" >&2
 exit 1
fi
awk 'length($0)>80 {print "FAIL: GITVREF record >80 columns:", NR; bad=1}
     END {exit bad}' "$v"
awk 'length($0)>80 {print "FAIL: GITREF2 record >80 columns:", NR; bad=1}
     END {exit bad}' "$r"
echo "M139 AUTHENTICATED FIRST SUBJECT GUARDS PASSED"
