#!/bin/sh
# M90 verified-ref bridge must stay read-only and CMS-record-safe.
set -eu
root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
v="$root/src/GITVREF.EXEC"
g="$root/src/GIT.EXEC"
r="$root/src/GITREF2.REPO"
rec="$root/src/GITREC.C"
test -s "$v"
test -s "$g"
test -s "$r"
test -s "$rec"
grep -Fxq "REF2 1" "$r"
grep -Fxq "HEAD refs/heads/main" "$r"
grep -Fxq "REF refs/heads/main 00D8D63229305230C8D37F884CE87F9E1A89468C" "$r"
grep -Fq "GITREC SHOWFULL GITFIX M15NEW" "$v"
grep -Fq "SHOW FULL ROOT CLOSURE VERIFIED" "$v"
grep -Fq "'FILEDEF SEL0 DISK M15SL0 PTR A'" "$v"
grep -Fq "'FILEDEF SEL1 DISK M15SL1 PTR A'" "$v"
grep -Fq "command = 'VERIFY-REF'" "$g"
grep -Fq "'EXEC GITVREF RESOLVE' rest" "$g"
grep -Fq "command = 'SHOW-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF SHOW' rest" "$g"
grep -Fq "command = 'LOG-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF LOG' rest" "$g"
grep -Fq "command = 'LOGDAG-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF DAG' rest" "$g"
grep -Fq "command = 'HISTORYPATH-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTPATH' rest" "$g"
grep -Fq "command = 'HISTORYCHANGES-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTCHG' rest" "$g"
grep -Fq "command = 'HISTORYEDGES-REF-FULL'" "$g"
grep -Fq "command = 'HISTORYDIFFS-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF HISTDIFF' rest" "$g"
grep -Fq "'EXEC GITVREF HISTEDGE' rest" "$g"
grep -Fq "command='HISTCHG'" "$v"
grep -Fq "HISTORYCHANGES FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYCHANGES DISTINCT PATH OIDS" "$v"
grep -Fq "HISTORYCHANGES STATUS' status" "$v"
grep -Fq "status='UNCHANGED'" "$v"
grep -Fq "status='CHANGED'" "$v"
grep -Fq "HISTORYCHANGES VERSION' vi 'OID' version.vi" "$v"
grep -Fq "'COUNT' freq.vi 'MINDEPTH' mindepth.vi" "$v"
grep -Fq "'MAXDEPTH' maxdepth.vi" "$v"
grep -Fq "curdepth=word(out.ci,5)" "$v"
grep -Fq "mindepth.distinct=curdepth" "$v"
grep -Fq "maxdepth.distinct=curdepth" "$v"
grep -Fq "parsednodes=parsednodes+1" "$v"
grep -Fq "if havepath=1 then return 'ERROR'" "$v"
grep -Fq "if parsednodes\\=nodes then return 'ERROR'" "$v"
grep -Fq "curcommit=translate(word(out.ci,3))" "$v"
grep -Fq "MINDEPTHCOMMIT' mincommit.vi" "$v"
grep -Fq "MAXDEPTHCOMMIT' maxcommit.vi" "$v"
grep -Fq "mincommit.distinct=curcommit" "$v"
grep -Fq "maxcommit.distinct=curcommit" "$v"
grep -Fq "HISTORYCHANGES VERSION' vi 'TYPE' vtype.vi 'SIZE' vsize.vi" "$v"
grep -Fq "curtype=word(out.ci,4)" "$v"
grep -Fq "cursize=word(out.ci,6)" "$v"
grep -Fq "if curtype<1 | curtype>3 then return 'ERROR'" "$v"
grep -Fq "if vtype.vi\\=curtype | vsize.vi\\=cursize then return 'ERROR'" "$v"
grep -Fq "HISTORYCHANGES VERSION' vi 'DEPTHS' depthtext.vi" "$v"
grep -Fq "depthtext.vi=result" "$v"
grep -Fq "vcommit.distinct.1=curcommit" "$v"
grep -Fq "vdepth.distinct.1=curdepth" "$v"
grep -Fq "vcidx=freq.vi" "$v"
grep -Fq "vcommit.vi.vcidx=curcommit" "$v"
grep -Fq "vdepth.vi.vcidx=curdepth" "$v"
grep -Fq "HISTORYCHANGES VERSION' vi 'COMMIT' vcommit.vi.ci" "$v"
grep -Fq "'DEPTH' vdepth.vi.ci" "$v"
grep -Fq "datatype(vdepth.vi.ci,'W')" "$v"
grep -Fq "curnode=word(out.ci,3)" "$v"
grep -Fq "curnode\\=parsednodes | curnode>64" "$v"
grep -Fq "seencommit.curcommit=1" "$v"
grep -Fq "curtree=translate(word(out.ci,3))" "$v"
grep -Fq "havetree=1" "$v"
grep -Fq "vnode.distinct.1=curnode" "$v"
grep -Fq "vtree.distinct.1=curtree" "$v"
grep -Fq "vnode.vi.vcidx=curnode" "$v"
grep -Fq "vtree.vi.vcidx=curtree" "$v"
grep -Fq "members=members+freq.vi" "$v"
grep -Fq "if members\\=nodes then exit 8" "$v"
grep -Fq "verify(vcommit.vi.ci,'0123456789ABCDEF')" "$v"
grep -Fq "verify(vtree.vi.ci,'0123456789ABCDEF')" "$v"
grep -Fq "HISTORYCHANGES VERSION' vi 'NODE' vnode.vi.ci" "$v"
grep -Fq "'TREE' vtree.vi.ci" "$v"
grep -Fq "depthseen.distinct.curdepth=1" "$v"
grep -Fq "depthseen.vi.curdepth=1" "$v"
grep -Fq "depthlist:" "$v"
grep -Fq "version.distinct=poid" "$v"
grep -Fq "vi=distinct" "$v"
grep -Fq "command='HISTPATH' & word(out.i,1)='HISTORYDAGPATH'" "$v"
grep -Fq "(word(out.i,2)='EDGE' | word(out.i,2)='EDGES')" "$v"
grep -Fq "freq.distinct=1" "$v"
grep -Fq "freq.vi=freq.vi+1" "$v"
grep -Fq "pathoids\\=nodes" "$v"
grep -Fq "GITREC HISTORYDAGPATH GITFIX M15NEW" "$v"
grep -Fq "HISTORYDAGPATH FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYDAGPATH EDGE CHILD %u PARENT %u" "$rec"
grep -Fq "HISTORYDAGPATH EDGES %u" "$rec"
grep -Fq "edge[head][pidx]=1" "$rec"
grep -Fq "nodeversion.curnode=vi" "$v"
grep -Fq "edgekey.ec.ep=1" "$v"
grep -Fq "parentseen.ep=1" "$v"
grep -Fq "if parentseen.1=1 then return 'ERROR'" "$v"
grep -Fq "HISTORYCHANGES CHANGED EDGES" "$v"
grep -Fq "HISTORYCHANGES UNCHANGED EDGES" "$v"
grep -Fq "CHILDVERSION' edgecv.ei" "$v"
grep -Fq "PARENTVERSION' edgepv.ei" "$v"
grep -Fq "STATUS' edgestatus.ei" "$v"
grep -Fq "command='HISTCHG' | command='HISTEDGE'" "$v"
grep -Fq "HISTORYEDGES FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYEDGES VERSIONS" "$v"
grep -Fq "HISTORYEDGES VERSION' vi 'OID' version.vi" "$v"
grep -Fq "HISTORYEDGES CHANGED EDGES" "$v"
grep -Fq "HISTORYEDGES UNCHANGED EDGES" "$v"
grep -Fq "HISTORYEDGES EDGE' ei 'CHILDVERSION' edgecv.ei" "$v"
grep -Fq "HISTORYEDGES EDGE' ei 'STATUS' edgestatus.ei" "$v"
grep -Fq "pairchild.pairs=cv" "$v"
grep -Fq "pairparent.pairs=pv" "$v"
grep -Fq "paircount.pairs=1" "$v"
grep -Fq "HISTORYEDGES TRANSITIONS" "$v"
grep -Fq "HISTORYCHANGES TRANSITIONS" "$v"
grep -Fq "HISTORYDIFFS FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "HISTORYDIFFS CHANGED EDGES" "$v"
grep -Fq "edgestatus.ei\\='CHANGED'" "$v"
grep -Fq "if distinct=1 & changededges\\=0 then exit 8" "$v"
grep -Fq "if distinct>1 & changededges=0 then exit 8" "$v"
grep -Fq "GITREC LOGDAGFULL GITFIX M15NEW" "$v"
grep -Fq "LOGDAG FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "GITREC LOGFULL GITFIX M15NEW" "$v"
grep -Fq "LOG FULL SNAPSHOTS VERIFIED" "$v"
grep -Fq "command='READ'" "$v"
grep -Fq "GITREC PATHFULLCAT GITFIX M15NEW" "$v"
grep -Fq "COMMIT ROOT FULL CLOSURE VERIFIED" "$v"
grep -Fq "command = 'READ-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF READ' rest" "$g"
grep -Fq "pathasciihex:" "$v"
grep -Fq "command='DIR'" "$v"
grep -Fq "GITREC PATHFULLDIR GITFIX M15NEW" "$v"
grep -Fq "command = 'DIR-REF-FULL'" "$g"
grep -Fq "'EXEC GITVREF DIR' rest" "$g"
if grep -Ei "(DISKW|ERASE|COPYFILE|GENWRITE|SELOUT|IDXOUT|FIDXOUT|GENOUT)" "$v"; then
 echo "FAIL: verified-ref bridge contains persistent write path" >&2
 exit 1
fi
awk 'length($0)>80 {print "FAIL: GITVREF record >80 columns:", NR; bad=1}
     END {exit bad}' "$v"
awk 'length($0)>80 {print "FAIL: GITREF2 record >80 columns:", NR; bad=1}
     END {exit bad}' "$r"
echo "M90 VERIFIED REF2 EDGE-ANALYSIS GUARDS PASSED"
